### ISSUE TITLE
Detect minimum version of parrot needed

### ISSUE THREAD

**Issue by leto** [parrot/cardinal#13]
Instead of blowing up like in #2

**Comment by lateau** [comment]
I can do this but I want to know is what the minimum version now?

Is the last supported version (=3.6.0) must be the minimum version?
I know cardinal nicely works on 3.3.0+

**Comment by leto** [comment]
I think checking for at least Parrot 3.3.0 and telling the user if they are using an older version is a good start. We can always increase the min version as it changes. Thanks for hacking on this!

**Comment by leto** [comment]
Done
