### ISSUE TITLE
Convert setup.pir to setup.winxed

### ISSUE THREAD

**Issue by leto** [parrot/cardinal#18]
Currently, maintaining setup.pir is getting onerous, so to -Ofun, we should convert it to Winxed.

Hey @lateau, this is all you.

**Comment by lateau** [comment]
AYE AYE SIR!

**Comment by leto** [comment]
This is a very good example: https://github.com/bubaflub/parrot-gmp/blob/master/setup.winxed

Cardinal will only need a subset of the stuff in parrot-gmp's setup.winxed. /cc @bubaflub

**Comment by lateau** [comment]
cardinal setup.winxed has clean and install now. this will spends 2~4days more, because I have not much time weekday.
if all stuff passed, I will request pull to cardinal.

**Comment by leto** [comment]
Thanks @lateau ! I accidentally closed this ticket.

**Comment by lateau** [comment]
this is done. close plz :)
